baseurl: ""

title: Sterling Crest - Expert in Bond Origination & Home Loans | Durban
email: sterling@evogroup.co.za
description: Contact Jacky and Jane from Sterling Crest to help you with your home loan. We are experienced property professionals specializing in home loans and property finance. We are passionate about the property industry, focusing on bonds, home loans, and origination. We are committed to excellence and building long-term relationships.
author: Pieter Oosthuizen

analytics:
  google: G-xxx

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/img/logo/logo.png

exclude: [node_modules, webpack-config.js, package.json, package-lock.json]

group: evo Homeloans

company: Sterling Crest

url: https://evohomeloans.co.za/

address: Durban, KZN

broadsheetApiUrl: https://ca-broadsheet-webapi.mangodesert-1e0c2940.westeurope.azurecontainerapps.io/
